# Julia Basics
> adapted from https://github.com/mitmath/julia-mit,
> https://algorithmsbook.com/validation/files/val.pdf#page=397

## Julia as a calculator

In [ ]:
3 + 4

In [ ]:
3 * 4

In [ ]:
3^4

In [ ]:
sin(3)

In [ ]:
1 / (1 + sin(pi/4))

## Variables

In programming languages, a `variable` is a named storage location that holds a value or data.

The variable name appears on the left side of the equal sign; the value that variable
is to be assigned is on the right side.

Variable names can be any string of characters, including Unicode, with a few restrictions.

In [ ]:
x = 17

In [ ]:
y = sin(x)

In [ ]:
α = 3.74 # Unicode variable name — type it by "\alpha<tab>"

In [1]:
?βᵗ

"βᵗ" can be typed by \beta<tab>\^t<tab>

search:

Couldn't find βᵗ
Perhaps you meant In, ;, >>, //, ≤, ⊽, &, |>, ?:, {, -, ", ~, ⊇, fd, √, ÷ or %


No documentation found.

Binding `βᵗ` does not exist.


In [ ]:
β₂ = sqrt(2) # Unicode variable name — type it by "\beta<tab>\_2<tab>"

#### Complex number:

In [2]:
z = 3 + 5im

3 + 5im

In [3]:
z^3

-198 + 10im

In [4]:
exp(z)

5.697507299833739 - 19.26050892528742im

In [5]:
sin(z)

10.472508533940392 - 73.46062169567367im

## Online help:

In [6]:
?sin

search: sin asin sinh sinc sign sind min in asinh sinpi asind stdin isinf using



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

See also [`sind`](@ref), [`sinpi`](@ref), [`sincos`](@ref), [`cis`](@ref), [`asin`](@ref).

# Examples

```jldoctest
julia> round.(sin.(range(0, 2pi, length=9)'), digits=3)
1×9 Matrix{Float64}:
 0.0  0.707  1.0  0.707  0.0  -0.707  -1.0  -0.707  -0.0

julia> sind(45)
0.7071067811865476

julia> sinpi(1/4)
0.7071067811865475

julia> round.(sincos(pi/6), digits=3)
(0.5, 0.866)

julia> round(cis(pi/6), digits=3)
0.866 + 0.5im

julia> round(exp(im*pi/6), digits=3)
0.866 + 0.5im
```

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


In [ ]:
?β₂

## Vectors

A vector is a one-dimensional array that stores a sequence of values. We can
construct a vector using **square brackets**, separating elements by commas or spaces:

Column vector; elements separated by commas:

In [2]:
x = [1, 17, 32, 15]  

4-element Vector{Int64}:
  1
 17
 32
 15

Row vector; elements separated by spaces:

In [3]:
[0 1 2] 

1×3 Matrix{Int64}:
 0  1  2

In [4]:
y = [15, 2, 6, -9];

In [5]:
x + y

4-element Vector{Int64}:
 16
 19
 38
  6

In [6]:
x * y # not allowed: vector * vector is not a linear-algebra operation

LoadError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})
The function `*` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:596
  *(::Dates.Period, ::AbstractArray)
   @ Dates ~/.julia/juliaup/julia-1.11.6+0.x64.linux.gnu/share/julia/stdlib/v1.11/Dates/src/periods.jl:93
  *(::LinearAlgebra.UniformScaling, ::AbstractVecOrMat)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.11.6+0.x64.linux.gnu/share/julia/stdlib/v1.11/LinearAlgebra/src/uniformscaling.jl:262
  ...


In [7]:

x' # or transpose(x)

1×4 adjoint(::Vector{Int64}) with eltype Int64:
 1  17  32  15

In [8]:

x' * y # allowed = a dot product

106

In [9]:
y * x'

4×4 Matrix{Int64}:
 15   255   480   225
  2    34    64    30
  6   102   192    90
 -9  -153  -288  -135

In [ ]:
x .* y # elementwise product

In [10]:
z = [3.7, 4.2, 6.1]

3-element Vector{Float64}:
 3.7
 4.2
 6.1

In [11]:

z .^ [0,1,2]

3-element Vector{Float64}:
  1.0
  4.2
 37.209999999999994

In [ ]:
z .^ [0 1 2]

In [ ]:
@show x
x[2] # second element

In [ ]:
x[2:3] # elements 2 to 3 — "slicing"

In [ ]:
x[2:4] # elements 2,3,4

In [12]:
2:4

2:4

In [13]:
typeof(2:4)

UnitRange{Int64}

In [14]:
collect(0:4)

5-element Vector{Int64}:
 0
 1
 2
 3
 4

In [ ]:
y .^ 3 # elementwise cube

In [ ]:
sin.(y) # elementwise sin

In [ ]:
collect(0:2:7) # 0 to 7 in steps of 2

In [ ]:
collect(0:0.1:7) # 0 to 7 in steps of 0.1

In [ ]:
r = range(0, 2π, 50) # 50 numbers from 0 to 2π, equally spaced

In [ ]:
collect(r)

In [ ]:
r = range(0, 2π, 10^8) # not computed explicitly

In [ ]:
collect(r[1:10])

In [ ]:
rand(5) # 5 random numbers in [0,1)

In [ ]:
randn(4) # 4 normally-distributed random numbers (mean 0, std. dev. 1)

In [15]:
x = [] # empty vector

Any[]

In [16]:
x = ones(3) # vector of three ones

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [17]:
x = zeros(3) # vector of three zeros

3-element Vector{Float64}:
 0.0
 0.0
 0.0

## Matrices

In [20]:
A = [1 3 7
     4 7 2
     0 1 1]

3×3 Matrix{Int64}:
 1  3  7
 4  7  2
 0  1  1

In [ ]:
B = [1 3 7; 4 7 2; 0 1 1]

In [ ]:
A == B

In [ ]:
b = [3, 2, 1] # a vector

In [ ]:
A * b # matrix-vector product

Let's solve a linear system $Ax = b$ for $x$:

In [ ]:
x = inv(A) * b  # Never!

In [ ]:
A * x

In [ ]:
A * x - b # not zero due to roundoff errors

Much better:

In [ ]:
x = A \ b # effectively equivalent to inv(A) * b, but faster and better

In [ ]:
A * x - b # slightly different (smaller in this case)

In [ ]:
sin.(A) # elementwise sine

In [ ]:
sin(A) # what does it mean?

## Functions

### Named functions

One way to define a named function is to use the `function` keyword, followed by
the name of the function and a tuple of names of arguments:

In [18]:
function f(x)
    return 3x^3 - 5x^2 + sin(x) - x
end

f (generic function with 1 method)

In [19]:
f(3)

33.141120008059865

In [21]:
f(A)

3×3 Matrix{Float64}:
 344.112    669.704  418.92
 688.962   1421.26   956.409
  87.4183   172.241  125.566

In [ ]:
f.(A) # applied elementwise

In [ ]:
f.(x) # applied elementwise

We can also define functions compactly using assignment form:

In [ ]:
g(x) = 4x^3 - 5x^2 + 6x + 2

In [ ]:
g.(A)

### Anonymous functions

An anonymous function is not given a name, though it can be assigned to a named
variable. One way to define an anonymous function is to use the arrow operator:

In [ ]:
h = x -> x^2 + 1 # assign anonymous function with input x to a variable h

In [ ]:
h(3)

In [ ]:
g(f, a, b) = [f(a), f(b)]; # applies function f to a and b and returns array

In [ ]:
g(h, 5, 10)

In [ ]:
g(x->sin(x)+1, 10, 20)

### Optional arguments

We can assign a default value to an argument, making the specification of that
argument optional:

In [ ]:
f(x=10) = x^2;

In [ ]:
f()

In [ ]:
f(3)

In [ ]:
f(x, y, z=1) = x*y + z;

In [ ]:
f(1, 2, 3)

In [ ]:
f(1, 2)

### Keyword arguments

Functions may use keyword arguments, which are arguments that are named
when the function is called. Keyword arguments are given after all the *positional
arguments*. A semicolon is placed before keywords, separating them from
the other arguments:

In [ ]:
f(; x = 0) = x + 1;

In [ ]:
f()

In [ ]:
f(x = 10)

In [ ]:
f(x, y = 10; z = 2) = (x + y) * z;

In [ ]:
f(1)

In [ ]:
f(2, z = 3)

In [ ]:
f(2, 3)

In [ ]:
f(2, 3, z = 1)

### Splatting

It is often useful to splat the elements of a vector or a tuple into the arguments to
a function using the ... operator:

In [ ]:
f(x,y,z) = x + y - z;

In [ ]:
a = [3, 1, 2];
f(a...)

In [ ]:
b = (2, 2, 0);
f(b...)

In [ ]:
c = ([1,2], [3,4], [5,6]);
f(c...)

## Control Flow

We can control the flow of our programs using *conditional evaluation* and *loops*.

### Conditional Evaluation

Conditional evaluation will check the value of a Boolean expression and then
evaluate the appropriate block of code. One of the most common ways to do this
is with an `if statement`:

In [26]:

x = -1 
y = 2

2

In [27]:

if x < y
    3*y   # run this if x < y
elseif x == y
    x + y # run this if x == y
else
    3*x   # run this if x > y
end

6

We can also use the *ternary operator* with its question mark and colon syntax.
It checks the Boolean expression before the question mark. If the expression
evaluates to true, then it returns what comes before the colon; otherwise, it
returns what comes after the colon:

In [ ]:
g(x) = x > 0 ? x : 0

In [ ]:
g(-10)

In [ ]:
g(10)

### Loops

A loop allows for repeated evaluation of expressions. One type of loop is the
*while* loop, which repeatedly evaluates a block of expressions until the specified
condition after the while keyword is met. The following example sums the values
of geometric series $1 + \frac{1}{2} + \frac{1}{2^2} + \ldots$ adding terms larger than 0.0001:

In [ ]:
x = 1
s = 0
while x > 0.0001
    s += x
    x /= 2
end

@show s;
@show x;

Another type of loop is the *for* loop, which uses the `for` keyword. The following
example will also sum over the values in the array X:

In [ ]:
X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
for y in X
    s += y
end

@show s;
@show X;

The `in` keyword can be replaced by `=` or `∈`.

## More Linear Algebra

Most linear-algebra routines are in the `LinearAlgebra` standard library:

In [ ]:
using LinearAlgebra 

In [ ]:
A = rand(3, 3)
A = A + A'

In [ ]:
eigvals(A) # eigenvalues

In [ ]:
F = eigen(A) # eigenvectors and eigenvalues

In [ ]:
F.values # the eigenvalues

In [ ]:
F.vectors # the eigenvectors

## Plotting

You must load a plotting library. There are lots to choose from. We are using PyPlot:

In [ ]:
using PyPlot

In [ ]:
x = rand(5)
plot(x, "bo-")
grid(true);

In [ ]:
x = range(0, 2π, 1000)
y = sin.(3x + 4cos.(2x))
plot(x / 2π, y, label=L"y")
plot(x / 2π, y.^2, label=L"y^2")
plot(x / 2π, 1 ./ sqrt.(1 .+ y.^2), label=L"\frac{1}{\sqrt{1+y^2}}")
xlabel("x / 2π")
ylabel("our funny function")
title("our second plot")
grid(true)
legend();

In [ ]:
?plot